import type { ChaosTheme, ThemeId } from '../types';

export const themes: Record<ThemeId, ChaosTheme> = {
  motherboard: {
    id: 'motherboard',
    label: '董事会彩虹油膜',
    background: '#f4ff00',
    foreground: '#12001f',
    accent: '#ff00b8',
    poison: '#00f0ff',
    border: '#5c00d8',
    fontMood: 'childlike',
  },
  synergy: {
    id: 'synergy',
    label: '企业级夜光肝脏',
    background: '#001b51',
    foreground: '#fff8c8',
    accent: '#36ff00',
    poison: '#ff6b00',
    border: '#ff00d4',
    fontMood: 'terminal',
  },
  marketplace: {
    id: 'marketplace',
    label: '婚庆电商季度大促',
    background: '#ffb7d5',
    foreground: '#3c003c',
    accent: '#b300ff',
    poison: '#fff000',
    border: '#00a651',
    fontMood: 'wedding',
  },
  oracle: {
    id: 'oracle',
    label: '思想领导力紫砂锅',
    background: '#21003f',
    foreground: '#fbffba',
    accent: '#ff6f00',
    poison: '#8cfffb',
    border: '#c8ff00',
    fontMood: 'tabloid',
  },
  compliance: {
    id: 'compliance',
    label: '可信治理洗浴中心',
    background: '#d6c4a8',
    foreground: '#141414',
    accent: '#0057ff',
    poison: '#8c4a00',
    border: '#ff2b2b',
    fontMood: 'corporate',
  },
  exit: {
    id: 'exit',
    label: '价值闭环安全出口',
    background: '#ca0000',
    foreground: '#ffffff',
    accent: '#ffe100',
    poison: '#00ffb7',
    border: '#1100ff',
    fontMood: 'terminal',
  },
};
