import type { ChaosTheme, ThemeId } from '../types';

export const themes: Record<ThemeId, ChaosTheme> = {
  motherboard: {
    id: 'motherboard',
    label: '董事会彩虹油膜',
    background: '#f4ff00',
    foreground: '#14002e',
    accent: '#ff0000',
    poison: '#00ff00',
    border: '#0000ff',
    fontMood: 'childlike',
  },
  synergy: {
    id: 'synergy',
    label: '企业级夜光肝脏',
    background: '#0000a8',
    foreground: '#ffff00',
    accent: '#ff0000',
    poison: '#00ff00',
    border: '#ff00ff',
    fontMood: 'terminal',
  },
  marketplace: {
    id: 'marketplace',
    label: '婚庆电商季度大促',
    background: '#ff69b4',
    foreground: '#000080',
    accent: '#00ff00',
    poison: '#ffff00',
    border: '#0000ff',
    fontMood: 'wedding',
  },
  oracle: {
    id: 'oracle',
    label: '思想领导力紫砂锅',
    background: '#220066',
    foreground: '#00ff00',
    accent: '#ff0000',
    poison: '#00ffff',
    border: '#ffff00',
    fontMood: 'tabloid',
  },
  compliance: {
    id: 'compliance',
    label: '可信治理洗浴中心',
    background: '#00ff00',
    foreground: '#000080',
    accent: '#ff0000',
    poison: '#ffff00',
    border: '#0000ff',
    fontMood: 'corporate',
  },
  exit: {
    id: 'exit',
    label: '价值闭环安全出口',
    background: '#ca0000',
    foreground: '#00ff00',
    accent: '#ffff00',
    poison: '#00ffff',
    border: '#0000ff',
    fontMood: 'terminal',
  },
};
