import type { ChaosTheme, ThemeId } from '../types';

export const themes: Record<ThemeId, ChaosTheme> = {
  motherboard: {
    id: 'motherboard',
    label: '董事会彩虹油膜',
    background: '#d6d775',
    foreground: '#2c2038',
    accent: '#b8443c',
    poison: '#6e913e',
    border: '#47428a',
    fontMood: 'childlike',
  },
  synergy: {
    id: 'synergy',
    label: '企业级夜光肝脏',
    background: '#29315c',
    foreground: '#e0d372',
    accent: '#a63f3f',
    poison: '#619055',
    border: '#874f8a',
    fontMood: 'terminal',
  },
  marketplace: {
    id: 'marketplace',
    label: '婚庆电商季度大促',
    background: '#d58fae',
    foreground: '#30345d',
    accent: '#69924a',
    poison: '#d6c758',
    border: '#4b4f8d',
    fontMood: 'wedding',
  },
  oracle: {
    id: 'oracle',
    label: '思想领导力紫砂锅',
    background: '#3d3158',
    foreground: '#86a96c',
    accent: '#b54b43',
    poison: '#6b9c9c',
    border: '#c7b858',
    fontMood: 'tabloid',
  },
  compliance: {
    id: 'compliance',
    label: '可信治理洗浴中心',
    background: '#7ea15d',
    foreground: '#33335c',
    accent: '#b34740',
    poison: '#d5c765',
    border: '#4c4f8b',
    fontMood: 'corporate',
  },
  exit: {
    id: 'exit',
    label: '价值闭环安全出口',
    background: '#8e3a36',
    foreground: '#79a765',
    accent: '#d0c45f',
    poison: '#6f9d9a',
    border: '#3f467d',
    fontMood: 'terminal',
  },
};
